name: AdjustExample
description: "Adjust Flutter Example App"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.9.0-277.0.dev

dependencies:
  flutter:
    sdk: flutter
  adjust_sdk:
    path: ../

dependency_overrides:
  characters: ^1.4.1
  material_color_utilities: ^0.13.0
  meta: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
