name: adjust_sdk
description: This is the Flutter SDK of Adjust™. You can read more about Adjust™ at adjust.com.
homepage: https://github.com/adjust/flutter_sdk
version: 4.35.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ">=1.1.6 <2.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.adjust.sdk.flutter
        pluginClass: AdjustSdk
      ios:
        pluginClass: AdjustSdk
